<?php

/**
* Implements hook_theme().
*/
function ice_cream_theme($existing, $type, $theme, $path) {
    return [
        'overview' => [
            'render element' => 'custom_page',
            'template' => 'overview',
            'variables' => ['flavors' => NULL, 'icecreamCount' => NULL, 'waffleCount' => NULL,  'languages' => NULL, 'ips' => NULL],
        ],
    ];
}

/**
 * Implements hook_mail().
 */
function ice_cream_mail($key, &$message, $params) {
$options = [
    'langcode' => $message['langcode'],
];
  switch ($key) {
      case 'node_insert':
          $message['subject'] = t('Your mail subject Here: @title', array('@title' => $params['title']), $options);
          $message['body'][] = $params['message'];
          break;
  }
}


